name: Tagged Deploy Cloudflare Worker

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install -g bun
      - run: bun remove better-sqlite3
      - run: bun install
      - run: bun run build
        working-directory: web
        env:
          CI: false
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.12.0 # See https://github.com/cloudflare/wrangler-action/issues/386
        with:
          workingDirectory: ${{ github.workspace }}/worker
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
